Courses
SamsonDeVol/cs493_final_project pull request #11
Opened 2023-06-07 21:33 UTC by jonahbroyer

check out my seqelize!

2023-06-07 21:35 UTC, SamsonDeVol requested changes
remove .env

2023-06-07 21:38 UTC, swearingenmj submitted a review, later dismissed
see comments

2023-06-07 21:38 UTC, swearingenmj commented on lib/sequelize.js
> +    database: process.env.MYSQL_DB_NAME,
make sure the variables match the .env file

2023-06-07 21:38 UTC, swearingenmj commented on models/course.js
> +  instructor_id: { type: DataTypes.INTEGER, allowNull: false }
lets go over this together. we should set some to NOT NULL and include foreign keys

2023-06-07 21:38 UTC, swearingenmj commented on models/course.js
> +User.belongsTo(Course)
add foreign key

2023-06-08 01:17 UTC, SamsonDeVol approved these changes

2023-06-08 01:19 UTC, merged